#cloud-config
write_files:
- owner: root:root
  path: /etc/ibm_attach_script.b64
  permissions: '0644'
  content: |
    ${attach_script}
- owner: root:root
  path: /root/setup_host.sh
  permission: '0755'
  content: |
    #!/bin/bash
    subscription-manager refresh
    subscription-manager release --set=7Server
    yum clean all
    subscription-manager repos --enable=*
    cat /etc/ibm_attach_script.b64 | base64 --decode > /etc/ibm_attach_script
    sleep 30
    yum clean all
    subscription-manager refresh
    bash /etc/ibm_attach_script

runcmd:
  - nohup bash /root/setup_host.sh

power_state:
  mode: reboot
  condition: True
