#cloud-config
write_files:
- owner: root:root
  path: /etc/ibm_attach_script.sh
  permissions: '0755'
  content: |
    ${attach_script}

runcmd:
#  - [ subscription-manager, refresh ]
#  - [ subscription-manager, repos, --enable, rhel-server-rhscl-7-rpms ]
#  - [ subscription-manager, repos, --enable, rhel-7-server-optional-rpms ]
#  - [ subscription-manager, repos, --enable, rhel-7-server-rh-common-rpms ]
#  - [ subscription-manager, repos, --enable, rhel-7-server-supplementary-rpms ]
#  - [ subscription-manager, repos, --enable, rhel-7-server-extras-rpms ]
  - [ subscription-manager release --set=7Server ]
  - [ yum clean all ]
  - [ subscription-manager refresh ]
  - [ subscription-manager repos --enable=* ]
  - [ nohup bash /etc/ibm_attach_script.sh ]

power_state:
  mode: reboot
  condition: True
